DELIMITER $$

CREATE FUNCTION StanPokojuWDniu(nNUMER_POKOJU INT, dDATA DATE) 
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE czy_zajety INT;
    SELECT COUNT(*) INTO czy_zajety
    FROM POBYT
    WHERE NUMER_POKOJU = nNUMER_POKOJU
      AND dDATA BETWEEN DATA_POCZATKU AND DATA_KONCA;
    IF czy_zajety > 0 THEN 
        RETURN 0;
    ELSE
        RETURN 1;
    END IF; 
END $$

DELIMITER ;
