DELIMITER $$

CREATE PROCEDURE UzupelnijMinibar(
    IN iID_POBYTU INT, 
    IN iP1 INT, IN iP2 INT, 
    IN iP3 INT, IN iP4 INT, 
    IN iP5 INT, IN iP6 INT, 
    IN iP7 INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION 
    BEGIN
        ROLLBACK;
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'BŁĄD: Nie udało się dodać produktów. Transakcja wycofana.';
    END;

    START TRANSACTION;

    IF iP1 IS NOT NULL THEN INSERT INTO ZUZYCIE (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP1, iID_POBYTU, NOW()); END IF;
    IF iP2 IS NOT NULL THEN INSERT INTO ZUZYCIE (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP2, iID_POBYTU, NOW()); END IF;
    IF iP3 IS NOT NULL THEN INSERT INTO ZUZYCIE (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP3, iID_POBYTU, NOW()); END IF;
    IF iP4 IS NOT NULL THEN INSERT INTO ZUZYCIE (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP4, iID_POBYTU, NOW()); END IF;
    IF iP5 IS NOT NULL THEN INSERT INTO ZUZYCIE (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP5, iID_POBYTU, NOW()); END IF;
    IF iP6 IS NOT NULL THEN INSERT INTO ZUZYCIE (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP6, iID_POBYTU, NOW()); END IF;
    IF iP7 IS NOT NULL THEN INSERT INTO ZUZYCIE (ID_PRODUKTU, iID_POBYTU, DATA_ZUZYCIA) VALUES (iP7, iID_POBYTU, NOW()); END IF;

    COMMIT;
    
    SELECT 'Produkty zostały pomyślnie dodane do tabeli ZUZYCIE.' AS Status;

END $$

DELIMITER ;
