CREATE VIEW DzisiejszyStatusPokoju AS
SELECT 
    p.NUMER_POKOJU, 
    p.LICZBA_MIEJSC,
    pb.ID_POBYTU,
    CONCAT(k.IMIE, ' ', k.NAZWISKO) AS KLIENT_REZERWUJACY, 
    pb.DATA_POCZATKU,
    pb.DATA_KONCA,
    CASE 
        WHEN pb.DATA_POCZATKU = CURDATE() THEN 'Przyjazd dziś'
        WHEN pb.DATA_KONCA = CURDATE() THEN 'Wyjazd dziś'
        WHEN CURDATE() BETWEEN pb.DATA_POCZATKU AND pb.DATA_KONCA THEN 'W trakcie'
        ELSE 'Wolny'
    END AS STATUS_DNIA
FROM 
    POKOJ p 
LEFT JOIN POBYT pb ON p.NUMER_POKOJU = pb.NUMER_POKOJU
    AND CURDATE() BETWEEN pb.DATA_POCZATKU AND pb.DATA_KONCA
LEFT JOIN 
    KLIENT k ON pb.ID_KLIENTA = k.ID_KLIENTA;
