DELIMITER $$

CREATE TRIGGER tr_automatycznie_dodaj_do_gosc_INSERT
AFTER INSERT ON POBYT
FOR EACH ROW
BEGIN
    INSERT INTO GOSC (ID_POBYTU, IMIE, NAZWISKO, DATA_URODZENIA, NR_DOKUMENTU)
    SELECT 
        NEW.ID_POBYTU, 
        k.IMIE, 
        k.NAZWISKO,
        k.DATA_URODZENIA,
        k.NR_DOKUMENTU
    FROM KLIENT k
    WHERE k.ID_KLIENTA = NEW.ID_KLIENTA;
END $$

DELIMITER ;
DELIMITER $$

CREATE TRIGGER tr_automatycznie_dodaj_do_gosc_UPDATE
AFTER UPDATE ON POBYT
FOR EACH ROW
BEGIN
    INSERT INTO GOSC (ID_POBYTU, IMIE, NAZWISKO, DATA_URODZENIA, NR_DOKUMENTU)
    SELECT 
        NEW.ID_POBYTU, 
        k.IMIE, 
        k.NAZWISKO,
        k.DATA_URODZENIA,
        k.NR_DOKUMENTU
    FROM KLIENT k
    WHERE k.ID_KLIENTA = NEW.ID_KLIENTA;
END $$

DELIMITER ;
