ALTER FUNCTION "DBA"."StanPokojuWDniu"( IN nNUMER_POKOJU INT, dDATA DATE)
RETURNS INT
DETERMINISTIC
BEGIN
	DECLARE _czy_zajety INT;
    SET _czy_zajety=(
    SELECT COUNT(*)
    FROM POBYT
    WHERE NUMER_POKOJU=nNUMER_POKOJU
    AND dDATA BETWEEN DATA_POCZATKU AND DATA_KONCA
    );
    IF _czy_zajety>0 THEN RETURN 0;
    ELSE
	    RETURN 1;
    ENDIF;
END
