CREATE PROCEDURE "DBA"."UzupelnijMinibar"( 
    IN iID_POBYTU INT, 
    IN iP1 INT DEFAULT NULL, IN iP2 INT DEFAULT NULL, 
    IN iP3 INT DEFAULT NULL, IN iP4 INT DEFAULT NULL, 
    IN iP5 INT DEFAULT NULL, IN iP6 INT DEFAULT NULL, 
    IN iP7 INT DEFAULT NULL 
)
BEGIN
    IF iP1 IS NOT NULL THEN INSERT INTO "DBA"."ZUZYCIE" (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP1, iID_POBYTU, CURRENT TIMESTAMP); END IF;
    IF iP2 IS NOT NULL THEN INSERT INTO "DBA"."ZUZYCIE" (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP2, iID_POBYTU, CURRENT TIMESTAMP); END IF;
    IF iP3 IS NOT NULL THEN INSERT INTO "DBA"."ZUZYCIE" (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP3, iID_POBYTU, CURRENT TIMESTAMP); END IF;
    IF iP4 IS NOT NULL THEN INSERT INTO "DBA"."ZUZYCIE" (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP4, iID_POBYTU, CURRENT TIMESTAMP); END IF;
    IF iP5 IS NOT NULL THEN INSERT INTO "DBA"."ZUZYCIE" (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP5, iID_POBYTU, CURRENT TIMESTAMP); END IF;
    IF iP6 IS NOT NULL THEN INSERT INTO "DBA"."ZUZYCIE" (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP6, iID_POBYTU, CURRENT TIMESTAMP); END IF;
    IF iP7 IS NOT NULL THEN INSERT INTO "DBA"."ZUZYCIE" (ID_PRODUKTU, ID_POBYTU, DATA_ZUZYCIA) VALUES (iP7, iID_POBYTU, CURRENT TIMESTAMP); END IF;
    COMMIT;
    MESSAGE 'Produkty zostały pomyślnie dodane do tabeli ZUZYCIE.' TO CLIENT;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            MESSAGE 'BŁĄD: Nie udało się dodać produktów. Transakcja wycofana.' TO CLIENT;
END
