CREATE PROCEDURE "DBA"."WymeldujKlienta"(IN pPOBYT INT)
BEGIN
	DECLARE _suma_nocleg NUMERIC(10,2) = 0;
    DECLARE _suma_uslugi NUMERIC(10,2) = 0;
    DECLARE _suma_calkowita NUMERIC(10,2) = 0;

    SET _suma_nocleg =(
    SELECT
        CASE 
            WHEN DATEDIFF(day, POBYT.DATA_POCZATKU, POBYT.DATA_KONCA) = 0 THEN POKOJ.CENA_ZA_NOC
            ELSE DATEDIFF(day, POBYT.DATA_POCZATKU, POBYT.DATA_KONCA) * POKOJ.CENA_ZA_NOC
        END
    FROM POBYT
    JOIN POKOJ ON POBYT.NUMER_POKOJU = POKOJ.NUMER_POKOJU
    WHERE POBYT.ID_POBYTU = pPOBYT
    );
    
    SET _suma_uslugi =(
        SELECT SUM(USLUGA.CENA)
        FROM WYKORZYSTANE_USLUGI
        JOIN USLUGA ON WYKORZYSTANE_USLUGI.ID_USLUGI=DBA.USLUGA.ID_USLUGI
        WHERE WYKORZYSTANE_USLUGI.ID_POBYTU=pPOBYT
    );
    
    SET _suma_calkowita=_suma_nocleg+ISNULL(_suma_uslugi, 0);

    SELECT POBYT.ID_POBYTU, KLIENT.NAZWISKO, KLIENT.IMIE, POBYT.NUMER_POKOJU,
    _suma_nocleg, _suma_uslugi, _suma_calkowita, POBYT.PLATNOSC
    FROM POBYT JOIN KLIENT ON POBYT.ID_KLIENTA=KLIENT.ID_KLIENTA
    WHERE POBYT.ID_POBYTU=pPOBYT;
END
