CREATE VIEW "DBA"."EfektywnoscPracy" AS
SELECT PRACOWNIK.NAZWISKO, PRACOWNIK.IMIE, COUNT(SPRZATANIE.NUMER_POKOJU)AS LiczbaSprzatan
FROM PRACOWNIK, SPRZATANIE
WHERE PRACOWNIK.ID_PRACOWNIKA=SPRZATANIE.ID_PRACOWNIKA
GROUP BY PRACOWNIK.ID_PRACOWNIKA, PRACOWNIK.NAZWISKO, PRACOWNIK.IMIE
ORDER BY LiczbaSprzatan DESC;
