CREATE VIEW "DBA"."DzisiejszyStatusPokoju" AS
SELECT p.NUMER_POKOJU, p.LICZBA_MIEJSC, pb.ID_POBYTU,
    k.IMIE || ' ' || k.NAZWISKO AS KLIENT_REZERWUJACY, pb.DATA_POCZATKU,
    pb.DATA_KONCA,
    CASE 
        WHEN pb.DATA_POCZATKU= CURRENT DATE THEN 'Przyjazd dziś'
        WHEN pb.DATA_KONCA= CURRENT DATE THEN 'Wyjazd dziś'
        WHEN CURRENT DATE BETWEEN pb.DATA_POCZATKU AND pb.DATA_KONCA THEN 'W trakcie'
        ELSE 'Wolny'
    END AS STATUS_DNIA
FROM 
 DBA.POKOJ p LEFT JOIN  DBA.POBYT pb 
ON p.NUMER_POKOJU pb.NUMER_POKOJU 
    AND CURRENT DATE BETWEEN pb.DATA_POCZATKU AND pb.DATA_KONCA
LEFT JOIN 
    DBA.KLIENT k ON pb.ID_KLIENTA = k.ID_KLIENTA
