CREATE MATERIALIZED VIEW "DBA"."PopularnoscUslug"
IN "system" AS
SELECT 
    USLUGA.NAZWA_USLUGI,
    COUNT(WYKORZYSTANE_USLUGI.ID_USLUGI) AS Liczba_Wykorzystan,
    SUM(USLUGA.CENA) AS Laczny_Zysk
FROM USLUGA
LEFT JOIN WYKORZYSTANE_USLUGI ON USLUGA.ID_USLUGI = WYKORZYSTANE_USLUGI.ID_USLUGI
GROUP BY USLUGA.NAZWA_USLUGI
