CREATE TRIGGER "tr_automatycznie_dodaj_do_gosc" AFTER INSERT, UPDATE
ORDER 2 ON "DBA"."POBYT"
REFERENCING NEW AS new_pobyt
FOR EACH ROW
BEGIN
    INSERT INTO "DBA"."GOSC" (ID_POBYTU, IMIE, NAZWISKO, DATA_URODZENIA, NR_DOKUMENTU)
    SELECT 
        new_pobyt.ID_POBYTU,  
        KLIENT.IMIE, 
        KLIENT.NAZWISKO,
        KLIENT.DATA_URODZENIA,
        KLIENT.NR_DOKUMENTU
    FROM "DBA"."KLIENT" 
    WHERE KLIENT.ID_KLIENTA = new_pobyt.ID_KLIENTA;
END
