CREATE TRIGGER "tr_dodawanie_do_gosc" BEFORE INSERT, UPDATE
ORDER 1 ON "DBA"."GOSC"
REFERENCING OLD AS old_name NEW AS new_name
FOR EACH ROW 
BEGIN
	IF EXISTS (
    SELECT GOSC.ID_POBYTU, COUNT(GOSC.ID_GOSCIA), POKOJ.LICZBA_MIEJSC
    FROM GOSC, POKOJ, POBYT
    WHERE GOSC.ID_POBYTU=POBYT.ID_POBYTU AND POBYT.NUMER_POKOJU=POKOJ.NUMER_POKOJU
    AND GOSC.ID_POBYTU = new_name.ID_POBYTU
    GROUP BY GOSC.ID_POBYTU, POKOJ.LICZBA_MIEJSC
    HAVING COUNT(GOSC.ID_GOSCIA)>= POKOJ.LICZBA_MIEJSC
    )
    THEN
    RAISERROR 20002 'Nie mozesz dodac wiecej gosci do tego pobytu'
    END IF
END
